# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      
    - name: Install dependencies
      run: git clone github.com/CinnamonDevGroup/Cinnamon &&
           go mod tidy


    - name: Build
      run: go build -tags minecraft -v &&
           env GOOS=windows go build -tags minecraft -v

    - name: Upload Compiled Windows Package
      uses: actions/upload-artifact@v3
      with:
        name: cinnamon.exe
        path: cinnamon.exe
      
    - name: Upload Compiled Linux Package
      uses: actions/upload-artifact@v3
      with:
        name: cinnamon
        path: cinnamon